WITH raw_samples AS (
    SELECT * FROM {{ source('onc_exp_lh', 'raw_samples') }}
)
SELECT
    id as sample_id,
    name as sample_name,
    internal_code,
    sample_type,
    created_by,
    CAST(created_at AS TIMESTAMP) AS created_at,
    CAST(updated_at AS TIMESTAMP) AS updated_at,
    CAST(run_date AS DATE) AS run_date,
    cell_line_name,
    cell_line_tissue_origin,
    cell_line_passage_number,
    plasma_fraction_type,
    plasma_donor_pool_size,
    plasma_pathogen_screening_status,
    plasma_storage_temperature_c,
    protein_source_material,
    protein_lysis_buffer,
    protein_yield_mg,
    protein_purity_percent,
    tumor_type,
    tumor_stage,
    tumor_collection_site,
    tumor_necrosis_percent,
    pbmc_donor_id,
    pbmc_viability_percent,
    pbmc_isolation_method,
    pbmc_cryopreserved,
    antibody_format,
    antibody_target_antigen,
    antibody_clone_id,
    antibody_binding_affinity_nm,
    antibody_humanized,
    record_hash,
    CAST(ingest_date AS DATE) AS ingest_date
FROM
    raw_samples