name: 'onc_exp_lh'
version: '1.0.0'

profile: 'onc_exp_lh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  onc_exp_lh:
    src:
      +materialized: view
