PROTOCOLS = [
    {
        "protocol_name": "Immune Receptor Flow Cytometry Assay",
        "protocol_code": "ICI-1001",
        "protocol_version": "v2.1",
        "is_antibody_relevant": False,
    },
    {
        "protocol_name": "T Cell Activation Co-Culture Assay",
        "protocol_code": "ICI-1002",
        "protocol_version": "v3.0",
        "is_antibody_relevant": False,
    },
    {
        "protocol_name": "Cytokine Release ELISA Assay",
        "protocol_code": "ICI-1003",
        "protocol_version": "v2.4",
        "is_antibody_relevant": True,
    },
    {
        "protocol_name": "Multiplex Cytokine Panel Assay",
        "protocol_code": "ICI-1004",
        "protocol_version": "v1.8",
        "is_antibody_relevant": True,
    },
    {
        "protocol_name": "Immune Cell Cytotoxicity Assay",
        "protocol_code": "ICI-1005",
        "protocol_version": "v2.2",
        "is_antibody_relevant": True,
    },
    {
        "protocol_name": "Checkpoint Reporter Gene Assay",
        "protocol_code": "ICI-1006",
        "protocol_version": "v2.7",
        "is_antibody_relevant": True,
    },
    {
        "protocol_name": "Serum Stability Study",
        "protocol_code": "ICI-1007",
        "protocol_version": "v1.9",
        "is_antibody_relevant": False,
    },
    {
        "protocol_name": "Pharmacokinetic Bioanalysis Assay",
        "protocol_code": "ICI-1008",
        "protocol_version": "v2.5",
        "is_antibody_relevant": False,
    },
    {
        "protocol_name": "Anti Drug Antibody Screen",
        "protocol_code": "ICI-1009",
        "protocol_version": "v2.0",
        "is_antibody_relevant": True,
    },
    {
        "protocol_name": "Dose Escalation Toxicology Study",
        "protocol_code": "ICI-1010",
        "protocol_version": "v3.1",
        "is_antibody_relevant": False,
    },
]

ANTIBODY_SCREENING_ASSAYS = {
    "ICI-1003": {
        "assay_category": "Cytokine Release",
        "assay_name": "Cytokine Release ELISA Assay",
        "endpoint_names": ["IL-2"],
        "endpoint_unit": "pg/mL",
        "instrument_names": ["SpectraMax i3x", "BioTek Synergy H1"],
        "value_range": (10, 3000),
        "treatment_concentrations": [0.1, 1, 10, 100],
        "measurement_timepoints_hours": [24],
        "replicates_per_measurement": 3,
        "antibody_candidates_per_result": (3, 6),
        "required_supporting_sample_types": ["pbmc"],
    },
    "ICI-1004": {
        "assay_category": "Cytokine Release",
        "assay_name": "Multiplex Cytokine Panel Assay",
        "endpoint_names": ["IL-2", "IFN-gamma", "TNF-alpha", "IL-6"],
        "endpoint_unit": "pg/mL",
        "instrument_names": ["Luminex MAGPIX", "Luminex FLEXMAP 3D"],
        "value_range": (10, 5000),
        "treatment_concentrations": [1, 10, 100],
        "measurement_timepoints_hours": [24, 48],
        "replicates_per_measurement": 2,
        "antibody_candidates_per_result": (3, 5),
        "required_supporting_sample_types": ["pbmc"],
    },
    "ICI-1005": {
        "assay_category": "Tumor Cell Killing",
        "assay_name": "Immune Cell Cytotoxicity Assay",
        "endpoint_names": ["Cytotoxicity"],
        "endpoint_unit": "%",
        "instrument_names": ["Incucyte SX5", "Agilent BioTek Cytation 5"],
        "value_range": (5, 95),
        "treatment_concentrations": [0.1, 1, 10, 100],
        "measurement_timepoints_hours": [24, 48, 72],
        "replicates_per_measurement": 3,
        "antibody_candidates_per_result": (2, 4),
        "required_supporting_sample_types": ["pbmc", "cell_line"],
    },
    "ICI-1006": {
        "assay_category": "Checkpoint Reporter Activity",
        "assay_name": "Checkpoint Reporter Gene Assay",
        "endpoint_names": ["Reporter Inhibition"],
        "endpoint_unit": "%",
        "instrument_names": ["Promega GloMax", "SpectraMax i3x"],
        "value_range": (0, 100),
        "treatment_concentrations": [0.01, 0.1, 1, 10, 100],
        "measurement_timepoints_hours": [6, 24],
        "replicates_per_measurement": 3,
        "antibody_candidates_per_result": (3, 6),
        "required_supporting_sample_types": ["cell_line"],
    },
    "ICI-1009": {
        "assay_category": "Antibody Binding",
        "assay_name": "Anti Drug Antibody Screen",
        "endpoint_names": ["Binding Affinity"],
        "endpoint_unit": "nM",
        "instrument_names": ["Octet RED96e", "Biacore T200"],
        "value_range": (0.01, 500),
        "treatment_concentrations": [1],
        "measurement_timepoints_hours": [0],
        "replicates_per_measurement": 2,
        "antibody_candidates_per_result": (4, 8),
        "required_supporting_sample_types": [],
    },
}