local: FALSE
s3_bucket: oncology-experimental-lakehouse

created_start: 2024-01-01
created_end: 2024-01-14

experiments:
    rows: 10
    signed_probability: 0.85
    signed_max_delay_days: 14
    witnessed_probability: 0.75
    witnessed_max_delay_days: 7

inventory:
    rows_samples: 8
    rows_stocks: 10